### ISSUE TITLE
Milestone #1

### ISSUE THREAD

**Issue by Suzii** [daliborjelinek/PV247-messaging-app#6]
# Status: ✔️ 
Below are just suggestions to consider for the next milestones.

Nice app with lovely profile pictures 😋 Cool that you are using typescript.
 
# Code suggestions
- Make all of your typescript interfaces readonly so that the compiler will help you to make sure you treat props state and other objects as immutable.
- Use lambdas for *all* class methods instead of binding them to `this` in constructor (e.g. getProfileMenuItems) (it is less error prone, and you also save code).
- I suggest you pass whole `message` object to `Message` component instead of the separate properties.

**Comment by tremors0** [comment]
Upraveno.
